### ISSUE TITLE
Doesn't work with Rust 1.79 on Debian

### ISSUE THREAD

**Issue by remitod** [codyps/buildid#11]
It used to work perfectly with Rust 1.75 on Debian (Docker image `rust:1.75-slim-bullseye`), but not anymore when I use Rust 1.79 (Docker image `rust:1.79-slim-bullseye`).

**Comment by codyps** [comment]
This is fixed in buildid v1.0.3. Cause is not entirely clear, but appears to be a change in how rust treats taking a reference of `fn()` items (ie: `&some_fn_item`). v1.0.3 removes that and uses the fn item directly. (Also includes a fix for windows which was making it dependent on how rustc decided to order some struct fields due to a missing `repr(C)`).

Thanks for reporting.

**Comment by remitod** [comment]
Thank you for your quick reply and fix!
